version: '3'
services:

  # React App
  web_page:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"  # Mapowanie portu 3000 na hosta

  # PHP App
  backend:
    image: php:apache
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8080:80"  # Mapowanie portu 8080 na hosta

  # MySQL Database
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ZAQ!2wsx
      MYSQL_DATABASE: osadnicy_db
      MYSQL_USER: db_osadnicy_user
      MYSQL_PASSWORD: Test123
    ports:
      - "3306:3306"  # Mapowanie portu 3306 na hosta

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ZAQ!2wsx
    depends_on:
      - mysql
    ports:
      - "8081:80"  # Mapowanie portu 8081 na hosta
